### ISSUE TITLE
Text Field placeholder is not properly localized in iOS 15

### ISSUE THREAD

**Issue by afterxleep** [afterxleep/Bouncer#10]
The localized string is present in localization files but using it directly in SwiftUI does not work in iOS 15 Beta 4.  It worked on iOS 14.

https://github.com/afterxleep/Bouncer/blob/ba8ec2c91faa92f1999cdc48dc4291c7ec01cba8/Bouncer/Views/FilterDetail/FilterDetailView.swift#L56

It works when manually adding `NSLocalizedString` though.

<img width="564" alt="Screen Shot 2021-08-27 at 12 36 49 AM" src="https://user-images.githubusercontent.com/1156669/131044894-6dcf09a0-dfc3-426c-9238-5c33e908788a.png">

**Comment by afterxleep** [comment]
The issue has been fixed in code by forcing NSLocalizedString, but leaving open as it needs to be updated as soon as Apple fixes the issue.

**Comment by asaah18** [comment]
Just wanted to let you know that _Arabic localization_ has the same problem with **empty strings** in localization file(they are empty for legitimate reason)

**Comment by afterxleep** [comment]
Thanks!. This is caused by SwiftUI in iOS 15.   I filed a Radar, but no response from Apple yet.

**Comment by asaah18** [comment]
Happy to help. 
While I have your attention, would you please check my pull request for Arabic localization(_it's only a necessary small change_)

**Comment by afterxleep** [comment]
Fixed in SwiftUI with iOS 15.2 and corrected in the app
