### ISSUE TITLE
capitalization

### ISSUE THREAD

**Issue by gregbonney-rgare** [afterxleep/Bouncer#15]
When I try to add a phrase like "Child Tax Credit" it becomes "child tax credit" instead and doesn't seem to match with the message.

**Comment by asaah18** [comment]
From my experience, the phrase being converted to lowercase didn't affect matching functionality

**Comment by afterxleep** [comment]
Hi @gregbonney-rgare 

The app converts all phrases to lowercase before saving, and it also lowercases message text before filtering.  This is expected behavior

Cheers!
