### ISSUE TITLE
Suggestion: "sender" naming is very confusing

### ISSUE THREAD

**Issue by yunyu** [afterxleep/Bouncer#16]
I installed Bouncer to block all numbers from AT&T email to SMS gateway starting with 1410, and it works great! I was just really confused at what "sender" meant – this is a really minor thing, but clarifying it as "sender number" would make it less confusing

**Comment by afterxleep** [comment]
Thanks for the input!.  I'll look into it!

**Comment by afterxleep** [comment]
This has been updated with 2.2.0
