### ISSUE TITLE
Allow the user to select if the provided text is a Regex or just plain text

### ISSUE THREAD

**Issue by afterxleep** [afterxleep/Bouncer#17]
Every string is being matched as a regular expression, which means some strings with dots and especial chars might be filtered incorrectly.

The solution to this would be adding a "checkbox" so the user can decide wether the string should be treated as regex or not.

**Comment by cglmrfreeman** [comment]
Could it be a toggle/switch instead of a checkbox?

**Comment by afterxleep** [comment]
The thing here would be figuring out how to deal with the elements you have already on your list and if we enable Regex by default or not.

**Comment by afterxleep** [comment]
I've added a setting to each filter individually that allows you to select "Regular" text matching or Regular expressions.

You can get the latest beta from TestFlight here:  https://testflight.apple.com/join/Lls6XUfx
