### ISSUE TITLE
cannot get past welcome/tutorial screen on iPhone SE

### ISSUE THREAD

**Issue by donaldchai** [afterxleep/Bouncer#18]
Running current version from Bouncer from the app store (version 2.1.1) on an iPhone SE (2016) with iOS 14.8.1.

The app is stuck on the welcome/tutorial screen, despite me going into the OS-wide settings and enabling SMS filtering.  (The screenshot below will make it clear why I thought that's all I needed to do.)

----

Based on reading the code:

https://github.com/afterxleep/Bouncer/blob/28b3fa157c5f3b75a344459f55cf4203841594f0/Bouncer/App/BaseView.swift#L17

https://github.com/afterxleep/Bouncer/blob/28b3fa157c5f3b75a344459f55cf4203841594f0/Bouncer/Views/Tutorial/TutorialContainerView.swift#L35

it seems like there's some sort of button that one is supposed to tap to get past this screen:

https://github.com/afterxleep/Bouncer/blob/28b3fa157c5f3b75a344459f55cf4203841594f0/Bouncer/Views/Tutorial/TutorialView.swift#L96

but the problem is that this button doesn't show up.

The iPhone screen resolution is 1136 × 640 and it seems like the TutorialView simply does not fit.  This is what it looks like on my screen:

![image](https://user-images.githubusercontent.com/14955603/148852291-fe687d9c-3247-4d39-8584-2174e75b0486.png)

**Comment by afterxleep** [comment]
You're right Donald.  You're not seeing the button due to the screen size.  I have not tested this on smaller screen devices and not sure if it's going to be easy to make that work, but I can try

**Comment by donaldchai** [comment]
FWIW I ended up working around this by mashing the screen at the bottom, and the button click registered somehow. :)

**Comment by afterxleep** [comment]
wow, that's bad UX, but glad you had It working.

**Comment by afterxleep** [comment]
Fixed with PR #28
