### ISSUE TITLE
Arabic Translation updates for 2.2.0

### ISSUE THREAD

**Issue by afterxleep** [afterxleep/Bouncer#23]
👋 hey @asaah18, I've updated some of the strings in the app and we likely need some updates.  Could you have a look?

You can open a PR to the `develop` branch with the updates, or just send them over here.

Cheers

**Comment by asaah18** [comment]
Sure, glad to be of help. Will do that as soon as possible.

**Comment by asaah18** [comment]
Done✔, please check the pull request #26

**Comment by afterxleep** [comment]
Thank you, merged!.  You'll see It in the next beta.
