### ISSUE TITLE
Filtered

### ISSUE THREAD

**Issue by blulegend** [afterxleep/Bouncer#31]
Bouncer is filtering messages to Junk even when there aren’t any rules for those messages. The messages for security codes and such and even some unknown numbers. The messages say filtered by bouncer at the bottom. And I have no filters for these types of messages.

**Comment by afterxleep** [comment]
This is an Apple behaviour.  Apple uses some internal filtering rules as soon as you enable a third party filter and marks that as "Filtered by Bouncer", but is not.   I hope they fix that in iOS 16
