### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by LoloParis** [afterxleep/Bouncer#32]
Dear sir 

can you add backup to save the list of word
In iCloud 

thank you

**Comment by afterxleep** [comment]
This is a good idea!.   I'll put that in the toDo list.

**Comment by afterxleep** [comment]
The next Beta 2.3.0 version allows you to export your block list, which should cover your backup needs :).  Will be available in the Testflight channel in a few minutes!

**Comment by LoloParis** [comment]
Dear sirThank you 😊 Le 23 avr. 2023 à 02:33, Daniel Bernal ***@***.***> a écrit :﻿
The next Beta 2.3.0 version allows you to export your block list, which should cover your backup needs :).  Will be available in the Testflight channel in a few minutes!
