### ISSUE TITLE
Idea: Would you be interested in including a basic machine learning Core ML model for spam?

### ISSUE THREAD

**Issue by spookyuser** [afterxleep/Bouncer#33]
- Love this app thank you for making it!

- I feel like most of my messages could easily be filtered to junk with a very basic ml model, could I take a shot at making a PR for this feature :)

**Comment by afterxleep** [comment]
That sounds interesting!.   Lets try it?

**Comment by spookyuser** [comment]
Awesome! I'll see what I can do!
