### ISSUE TITLE
Support Android

### ISSUE THREAD

**Issue by Github-contribute** [afterxleep/Bouncer#36]
Currently there is no opensource spam filter app for android. I recently I read article about bouncer SMS filter for iOS. Please support android my kind request🙏. At least pls consider don't close the issue. If make it, pls summit on fdroid also. @afterxleep

**Comment by afterxleep** [comment]
Unfortunately Android would requiere a completely different app, and I don’t think I’ll ever get to that, but if I ever do, I’ll let you know!
