### ISSUE TITLE
hyphens in messages are preventing matches

### ISSUE THREAD

**Issue by leres** [afterxleep/Bouncer#38]
**Describe the bug**
Recently I've seen cases where junk messages that I had pre-existing rules for  are not  being blocked. An example  string is:
`22-rep.com`
I think what's happening is that imessage (perhaps since I updated to IOS 16.0 a few days ago) is hyphenating urls when it breaks them up and the strings doesn't match:
`22-rep.-com`
(note hyphen)

**Screenshots**
Example screen grab from imessage:
![bouncer](https://user-images.githubusercontent.com/597247/190523312-a666275f-0b9e-4d71-8c7d-e89ad829b158.jpg)

**Desktop (please complete the following information):**
 - iOS Version: 16.0
 - Device: iPhone 12pro

**Comment by afterxleep** [comment]
Wow, this is bad.  URLs should not be modified by Messages and if it's done for presentation purposes, the contents of the message when read by the app shouldn't have hyphens. 

What happens if you copy/paste the URL?  Does it paste without hyphens?

**Comment by leres** [comment]
cut-n-paste does not include the hyphens.

I did some testing and could not reproduce. I suspect I added a new regex and forgot to click the "regex" button. Sorry for the unnecessary drama...

**Comment by afterxleep** [comment]
Okay.  No worries.  I'll close the issue, but if you're able to reproduce, let me know
