### ISSUE TITLE
Export/Import Ruleset

### ISSUE THREAD

**Issue by captn3m0** [afterxleep/Bouncer#40]
**Is your feature request related to a problem? Please describe.**
I'd like to onboard my friends to Bouncer, but asking them to create their own rules from scratch is not optimal.

**Describe the solution you'd like**
Send my friends a exported version of my ruleset/blocklist which they can import into Bouncer,

**Describe alternatives you've considered**
#39 

**Additional context**
Would make it easy to onboard my friends to Bouncer.

**Comment by afterxleep** [comment]
Thank you for reporting.   I think this is an excellent idea as a first step for syncing lists.  Let me think about it

**Comment by afterxleep** [comment]
This work is completed and merged to develop.  I'll be merging this to master soon and releasing on the next version.

**Comment by afterxleep** [comment]
Join the beta test here: https://testflight.apple.com/join/Lls6XUfx
