### ISSUE TITLE
Sub-categories support in iOS 16

### ISSUE THREAD

**Issue by henryhchchc** [afterxleep/Bouncer#42]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add support for the detailed [sub-categories in iOS 16](https://developer.apple.com/documentation/sms_and_call_reporting/ilmessagefilterqueryresponse/3929824-subaction).

**Describe alternatives you've considered**
N/A

**Additional context**
Thanks for the great app. I hope the following links may be useful:
- https://9to5mac.com/2022/06/15/sms-filtering-api-more-categories-ios-16/
- https://developer.apple.com/documentation/sms_and_call_reporting/ilmessagefilterqueryresponse/3929824-subaction

**Comment by afterxleep** [comment]
Quick update on this, work is in progress.  I should have an update soon.

**Comment by luduoduo** [comment]
Really like this project and am looking forward to subcategories. When would you release that?

**Comment by afterxleep** [comment]
I've been a little busy, but still looking into this.  Also I've found that Apple enforces some limitations in the sense that you can only have 5 categories on each app, so I also need to figure out which ones to keep

**Comment by afterxleep** [comment]
Categories will be available in the next beta.  Apple limits the maximum number of categories per app to 5, so I picked the ones that are most useful.

<img width="549" alt="Screenshot 2023-04-23 at 2 32 06 AM" src="https://user-images.githubusercontent.com/1156669/233813124-c191cf4f-511c-471c-8c38-e20e2889fdff.png">

**Comment by afterxleep** [comment]
Join the beta test here: https://testflight.apple.com/join/Lls6XUfx
