### ISSUE TITLE
Delete action is deleting an unintended rule

### ISSUE THREAD

**Issue by kranthi209** [afterxleep/Bouncer#65]
**Describe the bug**

In the search results UI, when performing the swipe-to-delete action on a rule, the delete is not working. **Moreover, it’s deleting another rule.** 

![IMG_2889](https://github.com/afterxleep/Bouncer/assets/145174998/8ea88325-5193-4398-951e-2d3a54b3c816)
 

**To Reproduce**
1. Go to the Rules list
2. Tap on search and search for some random rule
3. Swipe to delete the rule
4. It would look like it got deleted, but then reappears again. _Moreover, it’s actually deleting some other rule_ (looks like the one “underneath” the search result). 

**Expected behavior**
In the search results, the rule on which the swipe-to-delete action is performed, has to be deleted. Other rules should not be affected.

**Screenshots**
Attached the screen where the issue is noticed.

**Desktop (please complete the following information):**
 - iOS Version: iOS 16.6.1
 - Device: iPhone 13

**Additional context**

**Comment by afterxleep** [comment]
Thank you for reporting.  This seems to be related to search.  I’ll have a look

**Comment by afterxleep** [comment]
This has been fixed and will be available in the next release
