### ISSUE TITLE
Filter not working for URLs?

### ISSUE THREAD

**Issue by NeoHBz** [afterxleep/Bouncer#71]
**Describe the bug**
Normally, the filters work, but in case the match is part of any URL, it fails unless an exact match is provided.

**To Reproduce**
1. Create Rule:
  - When: Any part of the message
  - Contains: domain.tld
  - Label: Junk
2. Wait for Message to arrive, eg:
`Message with more content containing sub.domain.tld/something123`

**Expected behavior**
Since we've added "domain.tld" as filter when "Any part of the message" contains "airtel.in", the message containing "sub.domain.tld/something123" should go to "Junk" as per the filter

**Screenshots**
Screenshot containing the rule:
<img src="https://github.com/afterxleep/Bouncer/assets/56602090/2d6ead75-f906-4675-b9e2-0eb669f44691" alt="bouncer_rule" width="300" />

Screenshot showing the message in Inbox - meaning it bypassed the Junk filter
<img src="https://github.com/afterxleep/Bouncer/assets/56602090/01d03c96-b2bf-4289-b206-9820842e13c1" alt="message_in_inbox" width="300" />

**Desktop (please complete the following information):**
 - iOS Version: 18 DB2
 - Device: iPhone 14 Pro Max

**Comment by afterxleep** [comment]
Thanks for the report.  Did this filter work on iOS 17?


On July 2, 2024, Github Notifications ***@***.***> wrote:
> Describe the bug
>  Normally, the filters work, but in case the match is part of any URL,
> it fails unless an exact match is provided.
>
> To Reproduce
>  Steps to reproduce the behavior:
>
> 1. Create Rule:
>
>  *  When: Any part of the message
>  *  Contains: domain.tld
>  *  Label: Junk
>
> 1. Wait for Message to arrive, eg:
>     Message with more content containing sub.domain.tld/something123
>
> Expected behavior
>  Since we've added "domain.tld" as filter when "Any part of the
> message" contains "airtel.in", the message containing
> "sub.domain.tld/something123" should go to "Junk" as per the filter
>
> Screenshots
>  Screenshot containing the rule:
> IMG_4086.PNG (view on web)
> <https://github.com/afterxleep/Bouncer/assets/56602090/2d6ead75-f906-
> 4675-b9e2-0eb669f44691>
>
> Screenshot showing the message in Inbox - meaning it bypassed the Junk
> filter
>  IMG_4085.jpg (view on web)
> <https://github.com/afterxleep/Bouncer/assets/56602090/01d03c96-b2bf-
> 4289-b206-9820842e13c1>
>
> Desktop (please complete the following information):
>
>  *  iOS Version: 18 DB2
>  *  Device: iPhone 14 Pro Max
>

—
Reply to this email directly, view it on GitHub
<https://github.com/afterxleep/Bouncer/issues/71>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAI2MPLPDNBCPLL3UNNCZETZKKAGLAVCNFSM6AAAAABKHI6RS2VHI2DSMVQWIX3LMV43ASLTON2WKOZSGM4DKOJQG4YDEMY>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by afterxleep** [comment]
@NeoHBz Did you tested this using iOS 17?   Could you please provide the exact text of the message to run some local tests?

Thanks!

**Comment by NeoHBz** [comment]
> Did you tested this using iOS 17?

Couldn't get access to iOS 17 to test this, sorry.

> Could you please provide the exact text of the message to run some local tests?
```
Sender: AD-AIRTEL
Message:
Last day to save upto Rs. 200! 
Recharge before prices change i.airtel.in/RC1799
```

Exported JSON Rule from app:
```
  {
    "subAction": "none",
    "action": "junk",
    "type": "any",
    "phrase": "airtel.in",
    "id": "26060B0A-37E1-4D6B-8F9B-68694372272D",
    "caseSensitive": false,
    "useRegex": false
  },
  ```

**Comment by NeoHBz** [comment]
Hi, I just noticed none of the filters are working on iOS 18 (Public Beta)

This ticket is now essentially a duplicate of https://github.com/afterxleep/Bouncer/issues/72
Closing.
