### ISSUE TITLE
Rules seemingly not filtering out messages on iOS 18

### ISSUE THREAD

**Issue by J-The-Fox** [afterxleep/Bouncer#72]
**Describe the bug**
Messages that seem to match to a rule(s) aren't getting matched and failing to get put into junk while still notifying me that there is new message

**To Reproduce**
1. Create a rule (either with regex or not)
2. Have a text message come in with a word that should match the rule
3. The text message is not filtered to junk and I get notified for it

**Expected behavior**
The text message matching the rule specified gets filtered to junk and I don't get notified

**Screenshots**
The rule in question:
![image](https://github.com/user-attachments/assets/c0e7af21-bc20-42bb-b6c0-ddf09407d003)

The message in question:
![image](https://github.com/user-attachments/assets/0aed934f-2051-49d0-8580-95a7c0a143b9)

**Desktop (please complete the following information):**
 - iOS Version: iOS 18 Developer Beta 3 (22A5307f)
 - Device: iPhone 11

**Additional context**
I'm not 100% sure if it's something that I'm doing wrong on my end or not. I would imagine though that the rule created should match the countless text messages I am receiving with that word in the message text

**Comment by sguth-affirm** [comment]
I'm having similar issues, on the latest public beta of iOS 18

**Comment by afterxleep** [comment]
IOS 18 has changed something in the Message handler extension.  Compiling the app with XCode 16 beta fixes the issue.   I'll submit an update as soon as Apple allows it.

**Comment by afterxleep** [comment]
Closing this as version 2.5 and higher solves the issue.
