### ISSUE TITLE
iOS 17 Support

### ISSUE THREAD

**Issue by TellowKrinkle** [afterxleep/Bouncer#77]
iOS 18 has only been out for a few days, and some of us like to wait a bit for things to settle before large updates.  AFAIK the App Store allows downloading older versions if you've already purchased an app, but it doesn't seem to allow you to purchase a new application if your phone doesn't support it.

**Comment by afterxleep** [comment]
Hey, thanks for the feedback.  I'm 100% onboard.

 Unfortunately, iOS 18 introduced some breaking changes, causing the filtering not to work.

- If the app is compiled for iOS 17 (XCode 15), messages wont be filtered on iOS 18
- If the app is compiled for iOS 18 (XCode 16), messages will not be filtered on iOS 17 and earlier.

The only solution was to release and keep an older version for download that was compatible with earlier iOS versions.

**Comment by TellowKrinkle** [comment]
Ooh fun
Well I'll compile it locally for now then
