### ISSUE TITLE
Filtered messages are still forwarded when "Text Message Forwarding" is active (Sonoma)

### ISSUE THREAD

**Issue by jarcoal** [afterxleep/Bouncer#79]
Forgive me if this works as expected in Sequoia, but I just wanted to call out that the "Text Message Forwarding" feature in iOS somewhat undermines the value of the app because even if a message is blocked, it slips through to other devices.

I'm guessing this is probably on Apple's side of the fence, but wanted to check just in case.

**Comment by afterxleep** [comment]
Thanks for reporting.  Unfortunately SMS forwarding does not respect any message filtering rules.  This is an Apple limitation.   We've been waiting for them to add this functionality for years now.

**Comment by jarcoal** [comment]
Makes sense, thanks for confirmation!
