### ISSUE TITLE
Arabic Strings requiring translation

### ISSUE THREAD

**Issue by afterxleep** [afterxleep/Bouncer#8]
@asaah18

I've added a couple of new strings in localization that were missing.   Could you take a look and update them?  (develop branch)

**Comment by asaah18** [comment]
> I have noticed some localization issues in the TestFlight version[2.1.1(build 136)]. I will check them and make a pull request to solve them as soon as possible.

Done, I have made a pull request for the updated ".strings" file in #12.

**Comment by asaah18** [comment]
Also, the dot in the numbering **(1. | 2. | 3. | 4.)** should be on the left side **(like this: ".1")** instead of the right side. They are on the "onboarding screen" and "help screen". I believe this shouldn't be hard for you to do.

**Comment by afterxleep** [comment]
Thanks, I'll see what I can do

**Comment by afterxleep** [comment]
@asaah18 Does this look OK to you?

<img width="564" alt="Screen Shot 2021-09-01 at 10 26 21 AM" src="https://user-images.githubusercontent.com/1156669/131638431-aaa63e0e-9f45-4420-b081-9d4861c61f31.png">

**Comment by asaah18** [comment]
Looks good 👍
